src/images/castleimages.pas
GPU-compressed date -> GPU-compressed data
=> Typo correction

src/ui/castlejoysticks.pas
Foundation of joystick support based on zengl.
=> Joystick support stumb / untested

fpmake.pp, src/ui/castlejoysticks.pas, src/ui/castleuicontrols.pas
New bunch of changes. Added line to fpmake.pp; Modified castleuicontrols.pas
=> Joystick support

src/images/castleimages.pas, src/images/castleimages_draw.inc
@michaliskambi you might want to double-check the changes. While straight-forward, I seem to be extremely inattentive today, so I might do something really silly :D
=> dmOverwrite in DrawFromCore

examples/localization/README.md, examples/localization/fonts/mk_fonts.sh, examples/localization/localization_test.lpi
To support for German special characters and make it compile cleaner.
=> Minor improvements to Localization test

src/ui/opengl/castlecontrols_scrollview.inc
TCastleScrollViewCustom.ScrollBarLeft
=> Option to place ScrollView ScrollBar on the left side

src/ui/opengl/castlecontrols_scrollview.inc
Sorry, I didn't test how it would be displayed. Now, hopefully, all formatting issues are fixed.
=> Fix pasdoc formatting

examples/curves/README.txt, examples/curves/data/my_curves.xml
Curves example just crash because there is no data file. 
This PR just add sample XML file and little readme how to create them.
=> Fix curves example

src/physics/kraft/kraft.pas
Latest version from https://github.com/BeRo1985/kraft master branch. Tested on Android and Linux.
=> Latest Kraft version, with #131 fixed and other improvements.

examples/physics/physics_2d_collisions/gameinitialize.pas, src/3d/castletransform.pas, src/3d/castletransform_physics.inc, src/game/castlescenemanager.pas
Allows change frequency and velocity integration scheme. Default values like in Kraft. 
Maybe we should check changes in `TSceneManagerWorld.Update` like `gravity` but I'm not sure if this is needed.
=> Access to physics settings in TCastleSceneManager

tools/castle-editor/code/castleundosystem.pas, tools/castle-editor/code/framedesign.pas
Select last edited cell in the last active tab during Undo/Redo; Improve Undo/Redo code
=> Castle editor undo selecting

tests/code/testcastlerandom.pas
Fix https://trello.com/c/QYekAxqL/53-rndrandom-can-sometimes-return-0
=> 53 fix random test

src/files/castleuriutils.pas, src/lcl/castledialogs.pas, tools/castle-editor/code/formproject.pas, tools/castle-editor/code/framedesign.pas, tools/castle-editor/code/visualizetransform.pas
Works in 2D and 3D, in case of no hitting any object, it takes default values of distance (3D - 20, In case of 2D try to use camera Z position or 100 if smaller than 100.
=> Ability to drag assets directly into the viewport

tools/castle-editor/code/formnewproject.lfm, tools/castle-editor/code/formproject.lfm
Fixes https://github.com/castle-engine/castle-engine/issues/244
=> Fix system tray icon hidden on non-main forms on Windows 10

tools/build-tool/code/tooltexturegeneration.pas
Make texture downscaling logic more straightforwards, bug-proof and obvious.
=> Change texture scaling logic

examples/platformer/code/gameenemy.pas, examples/platformer/code/gamefallingobstacle.pas, examples/platformer/code/gamestateplay.pas
Platformer PR to make https://github.com/castle-engine/castle-engine/pull/292 testing easier. Can be merged after https://github.com/castle-engine/castle-engine/pull/292.
=> Removal of setting TRigidBody.Exists after TCastleTransform.Exists.

src/delphi/vcl.castlecontrol.pas
published the VCL Mouse Events
=> New Flag for WMEraseBkgnd to avoid flicker

src/lcl/castledialogs.pas
=> Set InitialDir when TCastleOpen3DDialog execute

src/files/castlexmlcfginternal.pas
Fixes https://gitlab.com/EugeneLoza/vinculike/-/issues/1048 :D
=> Mark config as modified after TXMLConfig.Clear

src/base_rendering/castleglshaders.pas
Handle GL context close in TGLSLProgram
=> GLSL program context handling

tools/build-tool/castle-engine.dpr, tools/build-tool/code/toolproject.pas
Needed in our vscode extension.
=> Ability to read project search paths from build tool

src/audio/castlesoundengine_engine.inc, src/audio/castlesoundengine_playingsound.inc, src/transform/castlebehaviors_soundsource.inc
Add the missing Priority-Property to TCastlePlayingSound and TCastlePlayingSoundSource.
Resolves #615
=> Add Priority to TCastlePlayingSound and TCastlePlayingSoundSource.

src/deprecated_library/castleengine.h, src/deprecated_library/castleengine.lpr, src/deprecated_library/castlelib_c_loader.cpp, src/deprecated_library/castlelib_dynloader.pas
This is just simple adding of one more function library interface.
Thanks a lot for your support.
=> Add function to get Castle Engine version to library interface

tools/build-tool/data/custom_editor_template/castle_editor_automatic_package.lpk
=> Adds SynEdit and SynEditDsgn as required packages for the editor

src/deprecated_library/castleengine.h, src/deprecated_library/castleengine.lpi, src/deprecated_library/castleengine.lpr, src/deprecated_library/castlelib_c_loader.cpp, src/deprecated_library/castlelib_dynloader.pas
I've added a new function to (deprecated) library interface: CGE_SetNodeMultFieldValue
There is already a function to set SFxxx values, I need a function to set MFxxx values too. So this solves my problem and I can dynamically update the such fields too (tested).
Please merge it to master soon 🙏, so that I can merge it to other library-related branches (URL processing).
=> Add function to set MultField value to library interface
