fpmake.pp, packages/castle_base.lpk, src/base/castleclassutils.pas, src/base/castlestreamutils.pas, src/base/castleutils_math.inc, src/base/castlevectors.pas, src/base/castlevectors_dualimplementation.inc, src/x3d/x3dloadinternal3ds.pas
These changes fix some problems when using the engine on big endian systems.
First of there was a bug in TSimplePeekCharStream that affected the X3D reader and secondly at least the 3DS loader misbehaved. For this I've added a TStream helper that deals with reading (and writing) values in the correct endianess and this helper should be used in the future for reading (and writing) binary data. I've already corrected the 3DS loader and I'll adjust more as I get along with testing everything on my big endian machines (one PowerPC and one M68k), though I don't know how long that will take, so merging this already would be good.
=> Big endian fixes

src/images/castleimages.pas, src/images/castleimages_draw.inc
Hi, Michalis!
I've decided to make the pull request from the scratch because I'm not so confident in my understanding of git and I'm afraid to mess something up :) Yesterday I was struggling 4 hours just to finally "discard my fork" and re-fork it again :)
Finally I've re-implemented and extended dmBlendSmart and dmMultiply modes for all applicable image types. I've also extended dmBlendSmart=dmBlend for no-alpha destination as it produces expected results.
Practically there is no sense in dmBlendSmart for no-alpha source, as it'll just replace the original image part and it's better to have an exception here because in this case the user is doing something that'll result in an unexpected result. However, it still might be extended in this sense to no-alpha / no-alpha blending.
I've also …
=> Re-implementation of dmBlendSmart and dmMultiply

src/base/castlelog.pas
Simplified the code by universalizing adding the time prefix.
Added a linebreak in multiline, now it looks like
-------------------- asdf begin
asdf
-------------------- asdf end
instead of
-------------------- asdf begin
asdf-------------------- asdf end
=> simplify WriteLogMultiline + add a line break after "Message"

tools/ss2x3dv/CastleEngineManifest.xml, tools/ss2x3dv/cocos2dparser.inc, tools/ss2x3dv/data/header.txt, tools/ss2x3dv/data/interpolator.txt, tools/ss2x3dv/data/route.txt, tools/ss2x3dv/data/shape.txt, tools/ss2x3dv/data/timesensor.txt, tools/ss2x3dv/ss2x3dv.lpi, tools/ss2x3dv/ss2x3dv.lpr, tools/ss2x3dv/ss2x3dv_compile.sh, tools/ss2x3dv/starlingparser.inc
I have created a simple utility allows to convert spritesheets into ready-to-use classic X3D format.
Support file format:
- Starling (.xml), Fully supported.
- Cocos2D (.plist). Covered most of important stuff, rare features like rotate, polygon sprites are not supported (yet!) but it can be added easily :).
Notes:
- By default anchor will be placed at the center of the sprite if the tool didn't found it in spritesheet.
- Frames must be named after the following format: XXX_YYY. XXX stands for frame name, which will be used as animation name. YYY is frame number. Example: slime_01.png, slime_02.png, ect.
- The tool is test on Windows only, but it should be able to compile on other OSes, as no platform-dependent code is used.
Demo clip from a previous development version but still applied …
=> Utility to convert spritesheets into classic X3D format.

src/ui/castlekeysmouse.pas, src/window/gtk/castlewindow_gtk.inc
I've added support for mouses with more than three buttons. Tested only in GTK window backend.
TMouseButton definition is compatible now with the one in the Controls unit.
=> Support for two extra mouse buttons

tools/build-tool/code/toolcompile.pas
CodeTyphon has its own FPC version with small modifications. One thing is its own Generics.Collection in a seperate package. That is why the build tool could not find the units. With a detection if CodeTyphon is installed, now, in this case, it will load the compatibility units like in FPC versions below 3.1.1.
Nicely the detection is very easy because on every supported platform the path to the modified FPC version contains the string "codetyphon".
=> Detection of CodeTyphon FPC with generics compatibility.

src/files/castlexmlconfig.pas
Simple thing: Why didn't "GetInteger" had an overload with a default value in the CastleXMLConfig? So, now it has.
=> Add GetInteger with default value overload to CastleXMLConfig.

packages/alternative_castle_window_based_on_lcl.lpk
In ce1b411b882c5660237051aa66162ad85706998c CastleDialogStates and CastleUIState were moved to ui/opengl into the castle_base.lpk. You forgot to remove if from alternative_castle_window_based_on_lcl.lpk.
=> Removed CastleUIState and CastleDialogStates from alternate_castle_window.

src/ui/opengl/castlecontrols_edit.inc, tools/build-tool/data/android/integrated/app/src/main/java/net/sourceforge/castleengine/ServiceAbstract.java, tools/build-tool/data/android/integrated/app/src/main/java/net/sourceforge/castleengine/ServiceMiscellaneous.java
I was able to change the toggle approach for the Android software keyboard with working `showSoftInput` and `hideSoftInput`, which makes it much less buggy in practical use.
Next to your suggestion to get the view via `getActivity().getWindow().getDecorView()`, it was necessary to use `InputMethodManager.SHOW_FORCED`.
Besides that, I had to extend the `stringToBoolean` function because the FreePascal `BoolToStr` used in CastleEdit wasn't compatible (anymore?). It returns `true` as `-1` and `false` as `0`. (When used in "string mode" it returns `True` and `False`, so this should cover most cases.)
=> Reliable showing/hiding of Android keyboard

examples/physics/physics_2d_collisions/gameinitialize.pas, examples/physics/physics_2d_game_sopwith/gameinitialize.pas, examples/physics/physics_3d_demo/gameinitialize.pas, src/3d/castletransform_physics.inc
As you probably noticed `TRigidBody.GetLinearVelocity()` has some problem. There is no 100% working way to check whether there is existing `FKraftBody` or that is just hanging pointer (so I have not added this check). It's because sometimes KraftEngine could be freed before `TCastleTransforms.DeinitializeTransform` call. Like in comment in `DeinitializeTransform`:
>  { FKraftBody is owned by FKraftEngine.
If FKraftEngine = nil then FKraftBody was already freed.
This can happen because TSceneManagerWorld.Destroy frees FKraftEngine,
but the TCastleTransform instances (with TRigidBody)
may be detached later, see TTestCastleTransform.TestPhysicsWorldOwner.
Because we currently have a pointer to our `TRigidBody` in UserData. I think we can fix it and have 100% certainty that this pointer is …
=> KraftRigidBody lifetime fix and expose some methods (WIP)

examples/physics/physics_2d_collisions/gameinitialize.pas, src/3d/castletransform_physics.inc
Little fix for first Castle Transform position update by `TransformationFromKraft`. After `TRigidBody.InitializeTransform` Kraft shape transform was not set properly. That makes strange effects before first physics step. See code comment for more info. Tested in my game ;)
=> Physics: Fix first castle transform position update.

src/services/castleads.pas, tools/build-tool/data/android/integrated-services/admob/README.md, tools/build-tool/data/android/integrated-services/admob/app/build.gradle, tools/build-tool/data/android/integrated-services/admob/app/src/main/AndroidManifest.xml, tools/build-tool/data/android/integrated-services/admob/app/src/main/java/net/sourceforge/castleengine/ServiceAdMob.java, tools/build-tool/data/android/integrated-services/google_play_games/app/build.gradle, tools/build-tool/data/android/integrated-services/google_play_services/app/build.gradle, tools/build-tool/data/android/integrated/app/src/main/java/net/sourceforge/castleengine/TAdWatchStatus.java
This PR adds rewarded ads to Admob service and fixes some problems I noticed in interstitial.
At this stage I added `ARewardedUnitId` to `InitializeAdMob()`. When you call `ShowFullScreenAd()` with `atReward` type reward video will be showed. `OnFullScreenAdClosed` has `Watched` set to `true` only when user should get reward. 
Currently there is no way to check why `Watched` is set to `false`. There is a lot of reasons like no advertising(ERROR_CODE_NO_FILL), no internet connection(ERROR_CODE_NETWORK_ERROR), internal admob error (ERROR_CODE_INTERNAL_ERROR), bad unit ID (ERROR_CODE_INVALID_REQUEST) or the ad is not loaded and we don't want to wait. I think we should add third attribute to `OnFullScreenAdClosed` but this will break compatibility.
I had a strange problem: sometimes ads …
=> Admob: Implemented rewarded ads and a lot of fixes in interstitial ads (WIP)

src/window/castlewindow_android.inc
In some cases context is not destroyed, so `ContextOpen` will not be called. Test case: share button click and return to app.
=>  Proper resume android activity after pause without context destroy (fixes sound missing after resume)

src/3d/castlecameras.pas
When I make pan gesture (two fingers from up to down) exception `Empty box 3d: no middle point, no sizes etc.` is raised. I found this in game menu, but most simple example is just empty window:
```
Window.Container.UIReferenceWidth := 1024;
Window.Container.UIReferenceHeight := 768;
Window.Container.UIScaling := usEncloseReferenceSize;
SceneManager := TCastle2DSceneManager.Create(Application);
SceneManager.FullSize := true;
SceneManager.ProjectionHeight := 768;
SceneManager.ProjectionAutoSize := false;
SceneManager.BackgroundColor := Gray;
Window.Controls.InsertFront(SceneManager);
```
Of course on Android device. This simple check fixes that.
=> TExamineCamera: Check FModelBox.IsEmpty when recognize pan gesture.

src/base/castletimeutils.pas
When I test my game, I noticed that sometimes (very rare, about one time on 20 minutes) the physics freezes, and moving rigid bodies appear about 2 centimeters further (on 5'' screen). Then I discovered that when this happens logs receive a lot of `Time: Detected gettimeofday () going backwards on Unix, workarounding. This is known to happen on some Android devices`. 
There can be about 300 lines with this information. So I tried to limit this logs. After that freezes still occur, but they are shorter, and don't affect physics so much (about 0.5 centimetre).
The log looks better also.
This PR limits this log to one occurrence.
=> Limit logs in Timer function to not affect performance

src/base/castletimeutils.pas, src/physics/kraft/kraft.pas
As I say in #131 Androdid have three clocks. I found that `clock_gettime(CLOCK_MONOTONIC)` uses clock that we need (https://stackoverflow.com/questions/3832097/how-to-get-the-current-time-in-native-android-code). 
Because Android is linux I use `clock_gettime(CLOCK_MONOTONIC, @tp);` from linux module. This works for me. I played 2 hours my game without any freezes :) Tomorrow will do more test. Please test this too on your projects/devices.
I also had to fix kraft. Do we use any special version? If I do PR in Kraft repo, will I be able to just use the latest version in CGE?
=> Fix Android time issue #131.

src/3d/castletransform.pas, src/3d/castletransform_physics.inc
Old collision detection events code was based on `TKraft.OnContactBegin`/`TKraft.OnContactEnd`. But sometimes there was two `OnContactBegin` events and one `OnContactEnd` or vice versa. That makes this event very hard to use in real code (for example double damage problem). This new approach based on `TKraftRigidBody.OnPostStep` cares to make only one `OnCollisionEnter` and only one `OnCollisionExit`. 
Extra feature `OnCollisionStay` - new event that is fired each physics frame when collision still remain. 
In addition, the code is only called for bodies that have `OnCollisionXXXX` event assigned. That should be faster.
=> New collision detection algorithm which cares about duplicate events - WIP

tools/build-tool/code/toolandroid.pas
FPC 3.2.0 supports AArch64 (https://forum.lazarus.freepascal.org/index.php?topic=42400.0).
=> Build tool: Set minimal FPC version that support 64-bit Android to 3.2.0

tools/build-tool/code/toolproject.pas, tools/build-tool/data/android/integrated-services/admob/app/build.gradle, tools/build-tool/data/android/integrated-services/google_play_games/app/build.gradle, tools/build-tool/data/android/integrated-services/google_play_services/app/build.gradle
Upgrades:
- default API level increased 28 to comply with Google requirements
- Google Services, Google Play Services and Admob upgraded to versions from https://developers.google.com/android/guides/setup#split According to our conversation. Tested on android 4.1.1 and on newer devices. I tested only login and achievements on Google Play Services.
=> Android updates

src/base/castletimeutils.pas
After two weeks of tests, I think its time to remove these checks :)
=> Removed unneeded (after #132) time measurement test on Android.

src/physics/kraft/kraft.pas
This PR fixes kraft crash after add and delete rigid body in the same physics step. I have this problem in my game. When level starts I show "Get ready", start timer and set `SceneManager.TimeScale := 0;`. But user can go back to menu and select another level in this case Kraft rigid bodies are created and destroyed without making physics step. That make crash Kraft.
When you add `TKraftRigidBody` with new shape to Kraft physics (In `TKraftRigidBody.Finish`) it's calls `TKraftShape.SynchronizeProxies`. This procedure creates AABB box, adds it to proper AABBDynamicTree and to `fPhysics.fBroadPhase`. 
Destruction of the shape remove AABB box from AABB dynamic tree, but not remove it from `fPhysics.fBroadPhase`. When next physics step come physics engine try to make contact pair with this …
=> Fixed Kraft crash when you add rigid body that collides with other and remove it in the same physics step

src/window/castlewindow_android.inc
This PR fix `TCastleApplication.ProcessMessage` loop suspending when game was sent to background. Without this fix when game is in background the loop still works unnecessarily wasting battery and CPU.
Now the condition only checks for the existence of the window, I removed other conditions from the check. 
In android game we need suspend loop always when the app is in background. I think `AllowSuspendForInput` will never be true in "normal" game because of:
```
function TExamineCamera.AllowSuspendForInput: boolean;
begin
Result := false;
end;
```
The same in `TWalkCamera`.
```
function TCastleOnScreenMenu.AllowSuspendForInput: boolean;
begin
Result := false;
end;
```
```
function TCastleApplication.AllowSuspendForInput: boolean;
var
I: Integer;
begin
Result := not (
Assigned(OnUpdate) or …
```
=> Android: Fixed TCastleApplication.ProcessMessage loop suspending

examples/physics/physics_2d_collisions/gameinitialize.pas, src/3d/castletransform_physics.inc
Triggers implementation for `TRigidBody`. To make trigger just set `Trigger` property to true. 
Triggers use the same events as other rigid bodies `TRigidBody.OnCollisionEnter`, `TRigidBody.OnCollisionStay`, `TRigidBody.OnCollisionExit`.
I added simple trigger to `physics_2d_collisions` example (I think it will be expanded when we add more features to physics).
=> Triggers implementation for TRigidBody

tools/build-tool/code/castle-engine.lpi, tools/build-tool/code/castle-engine.lpr
I just needed to compile build-tool, but there was some unit lacks and error on project load:
```
The file "/home/and3md/fpc/castle_game_engine/tools/build-tool/code/toolarchitectures.pas" was not found.
```
Maybe you work on build-tool now, in that case just ignore(close) this PR, otherwise, this PR fixes the problem.
=> Fixed build-tool compilation.

tools/castle-editor/code/formchooseproject.pas
On Windows, when we hide the main form using TForm.Hide, the button on taskbar also got hidden.
It is better to set Application.ShowMainForm field on Windows instead.
=> castle-editor: Fixed taskbar button hidden on Windows

src/3d/castletransform.pas, src/3d/castletransform_physics.inc, src/base/castletimeutils_frameprofiler.inc
Avoid spiral of death when physics step get more time than rendering. When there are more than 5 steps per Update, next steps are abandoned and time reduced. Don't know how big should be default value, you can change it if you think it is too low/high.
This value can be changed by `MaxPhysicsTicksPerUpdate` in `TPhysicsProperties`. When you change it to `0` protection will not work. When you change it to `1` there will be one physics step per update so simulation will slow down on weak hardware.
Physics is in frame profiler now:
```
-------------------- FrameProfiler begin
Frame time: 0.02 secs (we should have 64.29 FPS based on this):
- BeforeRender: 0%
- Render: 94% (0.01 secs, we should have 68.38 "only render FPS" based on this)
- TCastleTransform.Render transformation: 2%
- …
```
=> Avoid spiral of death when physics step get more time than rendering + add physics to frame profiler.

packages/castle_base.lpk, src/x3d/x3dloadinternalspine.pas, src/x3d/x3dloadinternalspine_animations.inc, src/x3d/x3dloadinternalspine_attachments.inc, src/x3d/x3dloadinternalspine_bones.inc, src/x3d/x3dloadinternalspine_bonetimelines.inc, src/x3d/x3dloadinternalspine_deformtimelines.inc, src/x3d/x3dloadinternalspine_json.inc, src/x3d/x3dloadinternalspine_slots.inc, src/x3d/x3dloadinternalspine_weightedmeshtimelines.inc
This PR is an effort to add support for one of Spine's major features: Weighted mesh.
Things that have been done so far:
- Add deprecated warning to skinnedmesh attachment.
- Support for weighted mesh, by interpolating values between bone timelines.
- Make weighted mesh work with deform timeline.
- Additional frames for better transition, this will make animation more accurate in certain situation (rotation and non-linear interpolation types) in exchange for longer load time and more memory consumption.
- Non-linear interpolation type (Bezier curve) for weighted mesh (both bone timeline and deform timeline).
Limitations:
- Due to the way we handle weighted mesh (by baking every transformations, including bones, into TCoordinateInterpolatorNode), we cannot have a mix of weighted mesh …
=> Add support for Spine weighted mesh

src/ui/castlekeysmouse.pas
fixes https://trello.com/c/RN2UlE2P/24-bug-keyup-conflicts-with-twincontrolkeyup
=> 24 Rename keyArrowUp/keyArrowDown to avoid namespace conflict with TWinControl

tools/common-code/toolcompilerinfo.pas
Summary: On Linux (at least on Debian) official Lazarus+FPC binaries no longer create `lazarus` executable, but `lazarus-ide` in `/usr/bin/`.
Tested and working for me, however, might need confirmation from the original reporter.
Should fix https://github.com/castle-engine/castle-engine/issues/210 Also we've been discussing the issue on Discord.
=> Add lazarus-ide as alternative Lazarus executable name

examples/fps_game/gameinitialize.pas, src/3d/castletransform.pas, src/game/castlelevels.pas, tests/code/testcastlelevels.pas
This PR fix Player recreation issue. 
Trello issues:
- https://trello.com/c/VhnXB66N/60-fix-frogger3d-crashing-regression
- https://trello.com/c/oXmF5Pda/61-castle-game-regression
This fix simply reinitialize the camera/navigation after changing the Player. This works ok for level restart. 
I played with Frogger a bit longer and made an extra fix to fix problems when destroying an object causes changes to the camera settings, and then it is notified of these changes. What can cause SEGFAULT. Simply way to see this is change the order of creation/adding Player, and Level to scene (in Frogger3D) like this: 
```
FpsPlayer := TPlayer.Create(SceneManager);
//SceneManager.Items.Add(FpsPlayer);
//SceneManager.Player := FpsPlayer;
FpsPlayer.Blocked := true; // do not allow to move player in this …
```
=> Fix Frogger3d and castle-game regression

tools/castle-editor/code/framedesign.pas
Fixes https://trello.com/c/C66HVb5s/76-bug-assigning-wrong-name-for-the-component-renames-it-in-treeview-and-keeps-the-wrong-name
=> 76 : Wrap renaming in TreeView in try..except

tools/castle-editor/code/framedesign.pas
Workaround bug when we may have `ControlsTree.Selected = nil` in `TDesignFrame.PropertyGridModified` under some circumstances
Trello issue: https://trello.com/c/V6v2rBwv/75-bug-access-violation-in-castle-editor
=> 75 bug access violation in castle editor

src/window/castlemessages.pas
This also fixes Frogger3d  "Enter key case" but also can help in other places.
Just all keys states are cleared after process messages loop quits. So keys state are correct after message box is closed.
Merging this before https://github.com/castle-engine/castle-engine/pull/220 will "hide" Frogger3d bug.
=> Message boxes should not leave keys in false/strange pressed state.

src/window/castlewindowprogress.pas
This also can fix Frogger3d but I add it more for another reason. The `TProgress` is visible when some long operations are made. So passing the state of the keys may trigger unnecessary responses, especially because of `TGLMode` can do `SimulateReleaseAll()`. 
This PR can also eliminate some of the weaknesses of TGLMode. But in the future (maybe after 7.0) we need totally rebuild TProgressBar (and messageboxes also?). 
I understand that TGLMode is supposed to enable state display without affecting the user-defined state stack. At first glance, in addition to the user stack, I would introduce something like `SystemState` that would be prioritized. If `SystemState = nil` then the user states would be used. Otherwise, the system state would take precedence. I don't know the implementation …
=> Clear pressed keys in progress bar. 

src/x3d/opengl/castleviewport.pas, src/x3d/opengl/glsl/generated-pascal/ssr.glsl.inc, src/x3d/opengl/glsl/source/ssr.glsl
This PR adds SSR screen effect to the engine.
The shader is based on Riccardo Balbo's implementation of SSR: https://github.com/riccardobl/SimpleSSRShader
TCastleViewport have 2 new properties:
- ScreenSpaceReflections: Enable(true)/Disable(false) SSR. Default is false.
- ScreenSpaceReflectionsSurfaceGlossiness: Adjust default surface glossiness (0..1). Default is 0.5.
Limitations:
- Since we lack various information about the scene (mainly because the engine doesn't have Deferred Rendering pipeline), the whole scene is reflectable - no bump mapping, roughness or metallic check.
- No filters (I can't figure out how best to implement it without resorting to low-level APIs).
Some screenshots:
=> Screen Space Reflections (SSR)

tools/build-tool/code/toolproject.pas
I changed the default target API level to 29 so the build tool meets the minimum Play Store requirements.
https://developer.android.com/distribute/best-practices/develop/target-sdk
Tested by compiling and running my game, drawing_toy, simple_3d_demo, 2d_dragon_spine_game.
=> Update default Android target API level to 29

src/ui/opengl/castletiledmap.pas, src/ui/opengl/castletiledmap_control.inc, src/ui/opengl/castletiledmap_map.inc
Hello,
this commit adds 
- rendering functionality for ObjectGroupLayers TiledObjects (polygon, polyline, point, rectangle) from TiledMaps
this commit doen't add
- rendering of ellipses
- rendering of labels of TiledObject
desired TODO feature
- transforming TiledObjects into TCastleUserInterfaces (perhaps based on TCastleShape?)
Let me know, what you think.
Have a nice day,
Matthias
=> Add basic rendering functionality for TiledObject primitives (Polygon, Polyline, Point, Rectangle)

tools/castle-editor/code/framedesign.pas
Fixes https://trello.com/c/kvAMJ3x2/116-it-is-possible-to-rename-component-in-castle-editor-to-empty-name-in-hierarchy
=> Check if component name is valid when renaming

tools/castle-editor/code/formproject.lfm, tools/castle-editor/code/formproject.pas
Save Castle Editor window state (maximized/minimized, width/height) and some internal parameters (three splitters positions) in UserConfig and load them upon reloading of the Form.
Fixes the first part of https://github.com/castle-engine/castle-engine/issues/216
=> Save castle editor window state

src/files/castleuriutils.pas
Currently on linux it removes filename with anchors (I think works as expected) but on windows its stops on last : in anchor URL.
I used `URIDeleteAnchor` with `RecognizeEvenEscapedHash=true` because GTK2 open dialog sometimes returns paths with # changed to `% code`. So i think this is more secure.
=> Fix ExtractURIPath() to work the same on all platforms

src/ui/opengl/castleuicontrols.pas
To avoid setting them into focused state after clicking a UI element in the same position (in this or previous state)
=> Do not set Focused state for TCastleUserInterfaces on Touch devices

src/files/castlexmlconfig.pas
Makes a clear warning in case TCastleConfig.Save is called before TCastleConfig.Load and thus nothing was saved.
Fixes https://trello.com/c/QSqKyIwu/120-if-userconfigload-is-not-called-userconfigsave-doesnt-save-anything
=> Log a warning in case TCastleConfig.Save is called before config file URL is known

src/images/opengl/castleglshaders.pas
This PR allows to set transform feedback varyings before linking a GLSL program.
This will be ignored if OpenGL ES is detected, and raise EGLSLTransformFeedbackError if OpenGL version is < 3.0
=> Allows to set transform feedback varyings

src/3d/castletransform_physics.inc
Because we set one kraft unit to one pixel (in the case of 2D). The default force of gravity `9.81` is very weak. This PR adds the ability to increase it in the physics settings (TPhysicsProperties.GravityStrength).
=> Implemented GravityStrength

src/3d/castletransform_physics.inc
Adds a capsule collider to our Kraft based physics. That is needed to create a platformer game.
=> Add Capsule collider to physics.

src/lcl/castlepropedits_color.inc, src/lcl/castlepropedits_exposetransforms.inc, src/lcl/castlepropedits_vector.inc, tools/castle-editor/code/framedesign.pas
Record Undo for TPropertyEditor values changes, including changing of the values through dialogue windows.
Fixes https://trello.com/c/oQu2Od2d/56-undo-in-editor-changing-colors-or-maybe-all-vectors-is-not-recorded-as-undo-item
Fixes https://trello.com/c/alED6w0E/123-minor-bug-changing-url-of-castleimagecontrol-doesnt-record-undo
=> Undo for property editor

src/window/castlewindow.pas
This should fix Xiaomi Mi 9 SE ARM64 bug that injects dangling external exceptions into the app. Note that this bug might also be related to the NS bug in TCasScriptExpression.Execute - and the workaround applied may fix it too.
Note that it was NOT TESTED on the Xiaomi phone - it was made based on a workaround that worked on the device.
=> ClearExceptions(false) on TCastleApplication.CastleEngineInitialize

src/physics/kraft/kraft.pas
This PR fix crash in Kraft sensor (our trigger) when you create `TRigidBody` after trigger (`TRigidBody` with `Trigger = True`) and make them collide.
Can be tested with https://github.com/and3md/cge-platformer-demo but you need my [platformer_fixes CGE branch](https://github.com/and3md/castle-engine/tree/platformer_fixes) to compile.
=> Fixed Kraft crash when rigid body touches sensor (trigger) and sensor was created before rigid body

src/3d/castletransform_physics.inc
This PR add `PhysicsRayCast()` to `TRigidBody`. It works using Kraft engine. From CGE `RayCast()` it differs by:
* you need set `MaxDistance` (in parent coordinate system)
* only kraft colliders are used - this ray can hit only physics object
* `Pickable` is not used - so you don't need make `Pickable` to true only on object you want to be raycastable in your game (what makes them also unselectable in editor). I think `Pickable` will be replaced with collision masks.
This PR is first step to make more things in CGE with real physics engine. Next we can start experimenting with collision masks and replacement of simplified CGE physics into a full physics engine.
This functionality is needed/can be tested by my platformer example https://github.com/and3md/cge-platformer-demo but you need my …
=> PhysicsRayCast implementation

src/3d/castletransform_physics.inc
In Kraft rigid body without `ksfCollision` still can be found by ray cast. But we don't want that when `TRigidBody.Exist = false`. This PR fixes that.
=> Not existing TRigidBody should not be ksfRayCastable (found by ray cast)

src/3d/castletransform_physics.inc
Fix PhysicsRayCast() return value: `TKraftRigidBody.UserData` is `TRigidBody` not `TCastleTransform`.
=> Fix PhysicsRayCast() return value

src/3d/castletransform.pas, src/castlescript/castlescript.pas, src/files/castlefilesutils.pas, src/images/castleimages_external_tool.inc, src/images/castlevideos.pas, src/images/opengl/castleglimages_load_2d.inc, src/x3d/opengl/castlerendererinternaltextureenv.pas, src/x3d/opengl/castleviewport.pas
accidentaly -> accidentally -  I found that when reading about Ray and just search/fix all docs.
https://whichiscorrect.com/accidentally-vs-accidentaly/
=> Fix typo in docs

tools/castle-editor/code/framedesign.pas
Gray color in UI often means that something is unavailable or not editable. My mind automatically filters them out and finding them is even harder. So this PR change color from gray to black. I also experimented with clNavy but triangle indicator highlight them enough and that is consistent with Lazarus.
Before:
After:
=> Change color of expandable properties from gray to black.

tools/castle-editor/code/visualizetransform.pas
In 2D gizmos can be really big. I changed algorithm to set scale about 15% of effective height. I also make them not grow/decrease when scale is changed - I think its more handy. Tested on platformer and 2d game template.
Before:
After:
=> Fix gizmo size in 2D (ptOrthographic)

tools/castle-editor/code/formproject.lfm, tools/castle-editor/code/formproject.pas
We talked about that once and I forgot. I couldn't decide Data should be after Code or after Run. Run seems to be related to Code so I added Data after it.
=> Data menu with New Sprite Sheet item

src/3d/castlecameras.pas, tools/castle-editor/code/framedesign.lfm, tools/castle-editor/code/framedesign.pas
This PR introduces a new type of navigation adapted to 2D games, and in particular, facilitating work in the editor on 2D games. Just press the right mouse button to easily move the content of the viewport. It's base on `TCastleExamineNavigation`. 
The way the camera works has been changed when `Camera.ProjectionType` is `ptOrthographic` (as we agreed in the interview). But maybe better solution is add property like `PixelPerfectMovement`, to not change the default behaviour of `TCastleExamineNavigation` which can also be useful or can break CGE users games.
=> Navigation for 2D (TCastle2DNavigation) 

src/ui/opengl/castletiledmap_map.inc
- this is needed/preparation for loading x3d nodes (see PR #241)
- this prevents redundant loading code for TMX files (here and for x3d nodes)
=> Load TMX files (Tiled Maps) by TStream/BaseUrl pair

examples/platformer/code/gamedeadlyobstacle.pas, examples/platformer/code/gamefallingobstacle.pas, examples/platformer/code/gamestateplay.pas
Fixes:
* fix using Push() with game over state
* fix spikes never ends hurting player
* once the spike hits the ground, it should no longer be able to hurt the player
* dead player shouldn't do anything
* set big friction on movable platforms only (TODO: player moves slower on them)
=> More work/fixes in Platformer demo

examples/platformer/code/gamestateplay.pas
Fixes https://trello.com/c/kK8wTdhj/158-platformer-errors-when-using-escape-to-go-to-options-from-game-when-dead-or-not-dead
=> Platformer demo: Pause game only when it's not paused (fixes crash).

src/ui/opengl/castletiledmap_map.inc
Patch 1) Set color property on loading of Tiled maps.
Patch 2) Fix typo in type name of Tiled object primitives.
=> Quick patches: Load color property + fix typo in type name (rel. to Tiled maps)

src/base/opengl/castleglversion.pas, src/images/opengl/castleglutils_information.inc, src/x3d/opengl/castlerendererinternalshader.pas, src/x3d/opengl/glsl/generated-pascal/bump_mapping_parallax.fs.inc, src/x3d/opengl/glsl/source/bump_mapping_parallax.fs
Running our 3d game template on all Android devices with Snapdragon (Adreno). Crashes randomly. On Medaitek, Exynos everything works ok. After investigation I found that these crashes are caused by BumpMapping (`bmSteepParallax` and `bmSteepParallaxShadowing` modes).  That's why we can't reproduce that in 2D games.
The solution is even weirder - in some cases `num_steps` can have random value. so We need add clamp:
```
vec3 v_to_eye = normalize(castle_vertex_to_eye_in_tangent_space);
float num_steps = mix(30.0, 10.0, v_to_eye.z);
#ifdef CASTLE_BUGGY_BUMP_MAPPING_NUM_STEPS
num_steps = clamp(num_steps, 10.0, 30.0);
#endif
float step = 1.0 / num_steps;
```
With this everything works OK.
I tested this fix on:
- Xiaomi Mi 10 Lite (M2002J9G), Snapdragon 765G, Adreno 620:
- Motorola Moto G8 …
=> Fix random crashes on Android Adreno devices 

src/base/opengl/castlegles.pas
OpenGL ES 3.0 APIs translate directly from Khronos's C header https://www.khronos.org/registry/OpenGL/api/GLES3/gl3.h with the help of `h2pas`.
=> Full OpenGL ES 3.0 header

src/ui/opengl/castletiledmap_map.inc
This PR re-opens and updates (closed) PR #317.
It adds 1 (important) fix and 1 feature related to loading of tilesets (from Tiled editor).
1) Fix (commit 4bef64b): If tiles were chosen from more than 1 tileset to populate a tile layer, the tiles were not correctly displayed due to a bug (all tilesets got FirstGID = 1). This got fixed. Every tileset has its actual FirstGID now.
See example (map64-two-tilesets.tmx) before and after applied fix. (Project code, see below)
2) Fix (other commits): If no special settings like probability are set in the Tiled editor for a tileset, the tiles are not explicitly written down in the tsx-file. In this case, the Tileset.Tiles (which is of type TTileList) is not populated. Only tiles which are explicitly found in the tsx-file are added. This doesn't …
=> Tiled: Populate tile list of tilesets correctly + Load from more than 1 tileset correctly

src/compatibility/delphi-only/uriparser.pas, src/files/castleuriutils.pas, tests/code/testcastleuriutils.pas, tests/delphi_tests/delphi_tests.dpr
I added some tests only for Windows, I will do more test (for unix) when when castle-tester will be ready.
=> Delphi: Fix Escape() Unescape() FilenameToURISafe() URIToFilenameSafe() 

src/3d/castletransform.pas, src/x3d/castlescenecore.pas, tools/castle-editor/code/framedesign.pas
This PR fixes https://github.com/castle-engine/castle-engine/issues/353
Also fixed selection bug after drop and removed hierarchy reload after drag'n'drop TCastleInterface (transforms need still do hierarchy reload).
=> Fix crash when drag'n'drop nodes in hierarchy on Windows

tests/CastleEngineManifest.xml, tests/code/testtoolfpcversion.pas, tests/test_castle_game_engine.lpi, tests/test_castle_game_engine.lpr, tools/common-code/toolfpcversion.pas
Fixes https://forum.castle-engine.io/t/0rc1-is-an-invalid-integer/492/3 however, only for this typical case of Lazarus 2.2.0RC1. Also added a test to make sure parsing goes as expected.
As this fix covers all current possible versioning variants for Lazarus on Windows, however in the past they've had quite bizarre version systems:
And current implementation will fail for such versioning, e.g.
* 0.9.30.2 will result in 0.9.30 version and will be seen as absolutely equal to 0.9.30.4RC3
* 1.0RC2 will throw an exception `0RC2 is invalid integer`
I'm not sure if we can "ignore" this. But anyway we now support two latest Lazarus release candidates versioning :)
=> Fix lazarus release candidate version parsing

src/base/castlestringutils.pas, src/window/windows/castlewindow_winapi.inc
I have an issue that view3dscene can't load a scene file of a path with multibyte characters because of garbling.
To improve this, I changed `TCastleWindowBase.BackendFileDialog` in `castlewindow_winapi.inc` to use `WideChar`.
In addition, I added these.
- a definition of struct `TOpenFilenameW` in `src\window\windows\castlewindow_winapi.inc`
- bindings to `comdlg32.dll` in `src\window\windows\castlewindow_winapi.inc`
- a function `PWideCharOrNil` in `src\base\castlestringutils.pas`
Former `castlewindow_winapi.inc` seemed to use the Ansi version of WinAPI (A suffix).
Environment:
Windows10 21H2 AMD64
Free Pascal Compiler version 3.2.2 [2021/05/15] for i386
=> fixed castlewindow_winapi.inc to use widechar

tools/castle-editor/code/projectutils.pas
Add also quotation marks as possible symbols in project name. See https://trello.com/c/6vmn9JKj/196-bug-project-name-caption-cannot-contain-special-characters
=> Add quotation marks to XML quote

src/scene/load/spine/x3dloadinternalspine_atlas.inc
This setting is useless for us (we control blending mode via `RenderOptions`), but causes exception because it's not yet handled.
=> Ignores premultiplied alpha setting when loading Spine atlas

src/ui/castlecontrols_button.inc
Just noticed that `TCastleButton` uses `Integer` instead of `TFingerIndex`. No harm done, but for consistency... :)
=> Use TFingerIndex in TCastleButton for consistency

.github/workflows/quick-test.yml
GH Action for Quick Test is now working on Windows. If you don't defined `shell: pwsh` the bash script is executed with gitbash, where `%PATH%` is different on Windows machines.
=> Enable Quick Test GH Action running on Windows

tools/castle-editor/code/formspritesheeteditor.pas
https://user-images.githubusercontent.com/26040454/212646669-a2843b78-de35-4b4c-85e5-10b952a72e14.mp4
This bug caused an endless loop and some incorrect actions.
```
while Item <> nil do
begin
if IsFrameListItem(Item) then
FSelectedFrames.Add(TCastleSpriteSheetFrame(Item.Data));
Item := FrameListView.GetNextItem(Item, sdBelow, [lisSelected]);
end;
```
When there is only one item, the loop never exits.
And It canot enum all selected items except for the items below it.
It should be **sdAll** and not **sdBelow**.
=> Fix FormSpriteSheetEditor

src/scene/x3d/x3dnodes_x3dnode.inc
This function is used to synchronize between different sprites.
Delete the original `TTimeSensor` route, and add the main sprite's `TTimeSensor` route.
I have tested it with examples, no problem.
=> declare RemoveRoute

src/files/castlexmlcfginternal.pas, src/files/castlexmlconfig.pas
Explicitly inform the user that "nothing was saved because there were no changes"
=> Avoid misleading log that config was saved when actually nothing was saved

src/lcl/castlepropedits_tiledlayers.inc
By simply adding space when there is only one digit in number.
Before:
After:
=> Fixed sorting of layers in TiledLayersPropertyEditor.

tools/build-tool/castle-engine.dpr, tools/common-code/toolcompilerinfo.pas
Added an option to get free pascal standard units paths used by vscode extension when freepascal installation does not have fpc.cfg.
=> An option to get free pascal standard units paths from build tool

.gitignore, examples/deprecated_library/cpp_winapi_library_tester/castlelib_win_tester.sln, examples/deprecated_library/cpp_winapi_library_tester/castlelib_win_tester.vcxproj, examples/deprecated_library/cpp_winapi_library_tester/main.cpp, examples/deprecated_library/qt_library_tester/qt_library_tester.pro, src/deprecated_library/castleengine.h, src/deprecated_library/castleengine.lpr, src/deprecated_library/castlelib_c_loader.cpp, src/deprecated_library/castlelib_dynloader.pas, src/scene/castlescenecore.pas
Changes to (deprecated) library:
1. new exported function to set InputShortcuts to Navigation
2. Fixed crash bug when reopening the scene using library interface (nilling MainScene pointer after close)
3. Better exception reporting - function name added
I've tested the functionality inside my app.
This pull request also fixes compilation of C++ example applications using the library interface (cpp_winapi_library_tester, qt_library_tester). I've also added some Visual Studio folders (used in cpp_winapi_library_tester) to gitignore to have the clean output.
Thanks
=> Update library interface with new function to set navigation input shortcuts

src/scene/castlesceneinternalshape.pas, src/scene/x3d/x3dnodes_standard_texturing.inc, src/scene/x3d/x3dnodes_x3dfonttexturescache.inc
Now when I know what the problem is, I'm surprised I didn't come up with the solution sooner :D
As we anticipated, the issue was in the cache, but in a different manner. After meticulously examining the `TX3DFontTexturesCache` code many times, I was convinced that the error lies elsewhere.
Each `TCastleScene` releases OpenGL resources when is destroyed. In that case cached, shared font texture is also removed on renderer side. That's why we don't have a crash but only visual garbage in other `TCastleText` instances. 
When `TCastleText` is destroyed it destroys also internal TCastleScene that in `TCastleTransform.Destroy()` calls `GLContextClose()`. That calls `TGLShape(Shape).GLContextClose;` Next `ShapesGLContextClose()` is called:
```
procedure TGLShape.GLContextClose;
if …
```
=> Font texture cache fix (hack) to solve OpenGL texture resources freeing when first TCastleText is released

src/ui/castlecontrols_groups.inc
I noticed that often when I add a group of controls, I have to go to the All tab to change paddings. I think they should be added to the Basic and Layout tabs, just like Spacing property. I added them to Vertical/Horizontal group because that property may be not important for other packed group descendants.
=> Add Padding to Basic/Layout inspector tab for TCastleVerticalGroup and TCastleHorizontalGroup

src/files/castledownload_asynchronous.inc, src/files/castledownload_url_http_fphttpclient.inc
There was two memory leaks: 
1. `FOwnsContents` was not set to `true`;
2. In case of the approach with unsafe `Thread.FreeOnTerminate := true;` the critical section was not freed
But I also created new a little funny solution that is safe, fast and enabled by default now. When `CASTLE_SAFE_DOWNLOAD_INTERRUPTION_CLEANING_THREAD` is defined. We create another cleaning thread that is `FreeOnTerminate = true` and waits for download thread termination. If you like it you can delete all old solutions and critical section freeing from `TFpHttpClientJob.Destroy;`
```
if (ParentThread <> nil) and (ParentThread.FreeOnTerminate) then
FreeAndNil(SynchronizationCS);
```
=> Fix memory leaks in TCastleDownload and proposal for faster and safe download thread freeing

src/ui/castleinternalsettings.pas
Fix a tiny typo "neded" -> "needed" in comment
=> fix a typo in comment

src/deprecated_library/castleengine.h, src/deprecated_library/castleengine.lpr, src/deprecated_library/castlelib_c_loader.cpp, src/deprecated_library/castlelib_dynloader.pas
It is handy to have the function to save scene to file (X3D, STL) in the (deprecated) library interface.
I've also added command to force modern rendering (GLFeatures.RequestCapabilities := rcForceModern;) for macOS, which is exactly on par how CastleControl and Cocoa backend work on macOS after requesting OpenGL CoreProfile.
Thanks.
=> Add scene saving function to deprecated library interface

tools/castle-editor/code/editorutils.pas
This will add auto-detection of VS Code on macOS. By default, VS Code is in Applications, and to call it with parameters in RunCommandNoWait, it is OK to use the executable from within the Visual Studio Code.app (the executable is called Electron).
This will fix the Issue #598
=> Autodetect VS Code on macOS for the Castle Editor

src/window/castlewindow_cocoa.inc
This PR implements clipboard on macOS (for example Ctrl+C didn't work in Castle Model Viewer on macOS), and also fixes the issue with retina monitor scaling with the current macOS SDK.
The code also reflects to dragging window to another screen (notification was not implemented before) and detects size changes by overriding the setFrameSize instead of NSViewGlobalFrameDidChangeNotification, which came far too often.
=> Cocoa backend fixes

src/window/castlewindow_cocoa.inc, src/window/castlewindow_cocoa_menu.inc, src/window/windows/castlewindow_winapi_menu.inc
This fixes the issue 100 in Castle Model Viewer (https://github.com/castle-engine/castle-model-viewer/issues/100), where UTF8 strings (e.g. viewpoints names, file names) with non-ASCII characters did not show correctly in menu items. 
Fixes:
1. WinAPI menu items (for viewpoint names and recent file names)
2. Cocoa menu items (for viewpoint names and recent file names)
3. Cocoa window title (for currently opened file name)
Not sure if NSString.stringWithUTF8String leaks or not, seems similar to NSSTR inline function (which calls CFStringMakeConstantString). I did a test in Activity monitor, did not see anything, so it should be probably fine or not so important.
=> Unicode menu items

.gitignore, examples/deprecated_library/qt_library_tester/glwidget.cpp, examples/deprecated_library/qt_library_tester/mainwindow.cpp
This also fixes most issues with invalid Qt framebuffers passed to CGE on all platforms.
=> Fixed Qt OpenGLWidget framebuffers handling in our Qt library example

src/window/castlewindow_cocoa_filedialog.inc
Implemented file filters in file-open/save dialogs Cocoa backed is a simple way, without combo box for now. But at least this gives automatic file extension (when user does not give any) in SaveDialog and visual file list filtering.
Lazarus can add file filter combo (as commented out in our code), but the code is very complex.
I suggest to keep this simple solution and wait until NSSavePanel.allowedContentTypes becomes available in FPC and implement file filter is using UTIs.
=> Implemented file filters in file-open/save dialogs Cocoa backend

examples/mobile/simple_3d_demo/data/CastleSettings.xml
... works much better on iOS
As discussed in issue #634 . This PR solves that issue.
=> Setting UIScaling to EncloseReferenceSizeAutoOrientation in simple_3d_demo

examples/deprecated_library/qt_library_tester/mainwindow.cpp, src/deprecated_library/castleengine.h, src/deprecated_library/castleengine.lpr, src/deprecated_library/castlelib_dynloader.pas
This option is super handy. Is by default on in Castle Model Viewer, so it would be good to provide a way to switch it on even in the library interface.
Thanks.
=> Adding PreventInfiniteFallingDown option to deprecated library

examples/deprecated_library/cpp_winapi_library_tester/main.cpp, examples/deprecated_library/lazarus_library_tester/cge_dynlib_tester_form.pas, examples/deprecated_library/qt_library_tester/glwidget.cpp, src/deprecated_library/castleengine.h, src/deprecated_library/castleengine.lpr, src/deprecated_library/castlelib_c_loader.cpp, src/deprecated_library/castlelib_dynloader.pas, src/deprecated_library/compile-iOS.sh
Related to removing ControlMouseDragMode in commit https://github.com/castle-engine/castle-engine/commit/6ff0c154548e361d166a4a9616c99bd0485d00cf
We need to address this in the deprecated library. The AutoNavigationViewport used there, so it seems the sufficient solution is to set WalkNavigation MouseDragMode when CGE_SetUserInterface(true) is called to set the automatic touch interface.
=> Set WalkNavigation MouseDragMode to rotate in deprecated library when automatic touch interface is set

.gitignore, src/common_includes/castleconf.inc, src/scene/load/x3dload.pas
This is only a suggestion, I don't expect that it would be merged to upstream, but let's see if @michaliskambi sees benefits of it.
For example I use only GLTF and SpriteSheets in my game, when I checked the castle-engine-output, I see big compiled files like castleicf and other similar from src/scene/load, I don't need support of those formats in Release build, and I know linker is not so smart to remove unused code, so I did it via conditional compilation (and it works as those modules are just pluggable, and no other module depend on them).
comparison (I defined all other formats disabling, except gtlf and spritesheet):
so the benefit is 2.5 mb, which is 20-25% of exe file size.
Ofc, this is not intended to be enabled by default, only by user who knows the outcome, and it makes sense …
=> User defined Disable of media formats, allows to shrink binary file

src/deprecated_library/castleengine.lpr
Put touch control over the screen in the library interface, else screen effects get applied to touch controls as well. This can be observed with SSAO or other ScreenEffects.
The change is only in the place where the controls are placed. We used to place them into Viewport, this PR puts them into Window.Controls, above the viewport.
=> Fix touch controls rendering in library interface
